# Generated by Django 5.0.dev20230410064954 on 2023-04-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answ', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.answer')),
                ('ques', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
            ],
        ),
    ]
