# Generated by Django 5.0.dev20230410064954 on 2023-04-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_answer_question_answer_votes_question_answ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='answ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.answer'),
        ),
    ]
