# Generated by Django 5.0.dev20230410064954 on 2023-04-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userprofile_answ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
        ),
    ]
