# Generated by Django 5.0.dev20230410064954 on 2023-04-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userprofile_user_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answ',
        ),
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='used',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='answ',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ques',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
