# Generated by Django 5.0.dev20230410064954 on 2023-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_answer_text_remove_answer_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
