# Generated by Django 5.0.dev20230410064954 on 2023-04-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_question_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='view',
        ),
    ]
